import { Inter } from "next/font/google";
import "./globals.css";
import Layout from "./components/Layout";
import { CssBaseline } from "@mui/material";
import NavBar from "./components/NavBar";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "PantryPal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>
       
          <Layout>
            <NavBar/>
          {children}
          </Layout>
        
        
        </body>
    </html>
  );
}
